# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-27 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanapp', '0007_auto_20180426_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraphs',
            name='blankflag',
            field=models.BooleanField(default=False),
        ),
    ]
