# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanapp', '0004_auto_20180325_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=400)),
                ('contract', models.FileField(upload_to='contracts')),
            ],
        ),
    ]
