# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-25 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanapp', '0002_auto_20180325_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='searchresult',
            name='content',
        ),
        migrations.AddField(
            model_name='searchresult',
            name='contents',
            field=models.ManyToManyField(related_name='Filename', to='lanapp.Content'),
        ),
    ]
