# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-17 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lanapp', '0005_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('last_changed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='last_changed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='title',
            field=models.CharField(default='default_title', max_length=400),
        ),
        migrations.AddField(
            model_name='contract',
            name='upload_time',
            field=models.DateTimeField(default='1970-01-01T00:00+00:00'),
        ),
        migrations.AddField(
            model_name='contractcomment',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lanapp.Contract'),
        ),
    ]
