# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-21 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanapp', '0010_paragraphs'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraphs',
            name='endflag',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
