# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-22 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lanapp', '0005_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('keyword', models.CharField(default='test_keyword', max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('last_changed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('last_changed', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lanapp.Content')),
            ],
        ),
        migrations.CreateModel(
            name='ContractComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('last_changed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paragraphs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('index', models.IntegerField()),
                ('highlight', models.BooleanField(default=False)),
                ('endflag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning', models.TextField(blank=True)),
                ('keyword', models.CharField(default='test_warning', max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('last_changed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WarningComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('last_changed', models.DateTimeField(auto_now=True)),
                ('warning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lanapp.Warning')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='last_changed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='title',
            field=models.CharField(default='default_title', max_length=400),
        ),
        migrations.AddField(
            model_name='contract',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='warning',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lanapp.Contract'),
        ),
        migrations.AddField(
            model_name='paragraphs',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lanapp.Contract'),
        ),
        migrations.AddField(
            model_name='contractcomment',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lanapp.Contract'),
        ),
        migrations.AddField(
            model_name='content',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lanapp.Contract'),
        ),
    ]
