# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-26 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanapp', '0006_auto_20180422_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraphs',
            name='warningflag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contract',
            name='title',
            field=models.CharField(default='No Title', max_length=400),
        ),
    ]
