# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-04 02:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lanapp', '0008_paragraphs_blankflag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentcomment',
            name='content',
        ),
        migrations.RemoveField(
            model_name='contractcomment',
            name='contract',
        ),
        migrations.DeleteModel(
            name='SearchResult',
        ),
        migrations.RemoveField(
            model_name='warningcomment',
            name='warning',
        ),
        migrations.DeleteModel(
            name='ContentComment',
        ),
        migrations.DeleteModel(
            name='ContractComment',
        ),
        migrations.DeleteModel(
            name='WarningComment',
        ),
    ]
