# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-04 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lanapp', '0009_auto_20180503_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('last_changed', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lanapp.Content')),
            ],
        ),
        migrations.AddField(
            model_name='paragraphs',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paragraphs',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lanapp.Content'),
        ),
    ]
