# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-04 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lanapp', '0011_content_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraphs',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lanapp.Content'),
        ),
    ]
